name: meetup_uy
channels:
  - conda-forge
dependencies:
  # Jupyter
  - notebook=5.7.8
  - tornado=5.1.1
  - nbconvert=5.4
  - widgetsnbextension=3.4
  - jupyter_nbextensions_configurator
  # Python Kernel
  - numpy==1.16.4
  - scikit-learn==0.21.2
  - scipy==1.2.1
  - matplotlib==3.1.0
  - seaborn==0.9.0
  - pandas==0.24.2